version: '3.8'

# Load environment variables from .env file
# Make sure to update .env with your production values

services:
  postgres:
    image: postgres:15
    container_name: portfolio-tracker-db-prod
    environment:
      POSTGRES_DB: portfolio_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: portfolio-tracker-backend-prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/portfolio_tracker
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
    ports:
      - "8087:8087"
    depends_on:
      - postgres
    networks:
      - portfolio-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: portfolio-tracker-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge


