version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: portfolio-tracker-db
    environment:
      POSTGRES_DB: portfolio_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-tracker-backend
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/portfolio_tracker
      DB_USERNAME: postgres
      DB_PASSWORD: password
      JWT_SECRET: mySecretKey
      ALPHA_VANTAGE_API_KEY: demo
    ports:
      - "8087:8087"
    depends_on:
      - postgres
    networks:
      - portfolio-network
    volumes:
      - ./backend:/app
      - /app/target

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-tracker-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8087/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - portfolio-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge


