services:
  - type: web
    name: portfolio-tracker-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /actuator/health
    rootDir: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8087"
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-tracker-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: portfolio-tracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-tracker-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: ALPHA_VANTAGE_API_KEY
        value: demo
      - key: ALPHA_VANTAGE_BASE_URL
        value: https://www.alphavantage.co/query
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:5177,http://localhost:5178,http://localhost:5179,http://localhost:5180,https://portfolio-tracker-latest-k69y.onrender.com"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      - key: SPRING_JPA_OPEN_IN_VIEW
        value: "false"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        value: "false"
      - key: LOGGING_LEVEL_COM_PORTFOLIOTRACKER
        value: INFO
      - key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
        value: WARN
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: portfolio-tracker-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: portfolio-tracker-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: portfolio-tracker-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE
        value: "20"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_VERSIONED_DATA
        value: "true"
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: "10"
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: "5"
      - key: SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT
        value: "300000"
      - key: SPRING_DATASOURCE_HIKARI_MAX_LIFETIME
        value: "1200000"
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: "20000"
      - key: SERVER_SERVLET_SESSION_TIMEOUT
        value: "30m"
      - key: SERVER_SERVLET_SESSION_COOKIE_SECURE
        value: "true"
      - key: SERVER_SERVLET_SESSION_COOKIE_HTTP_ONLY
        value: "true"
      - key: SERVER_SERVLET_SESSION_COOKIE_SAME_SITE
        value: strict
      - key: LOGGING_LEVEL_ORG_HIBERNATE_SQL
        value: WARN
      - key: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER
        value: WARN

databases:
  - name: portfolio-tracker-db
    plan: free
    region: oregon
