services:
  - type: web
    name: portfolio-tracker-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile.prod
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ALPHA_VANTAGE_API_KEY
        value: demo

databases:
  - name: portfolio-tracker-db
    plan: free
    region: oregon
